============================= test session starts ==============================
platform linux -- Python 3.12.11, pytest-8.4.1, pluggy-1.6.0
rootdir: /home/a/Development/21/intership/intership_tasks/Workmate
plugins: cov-6.2.1
collected 46 items

project/tests/e2e/test_full_workflow.py ....                             [  8%]
project/tests/e2e/test_full_workflow_with_pandas.py ....                 [ 17%]
project/tests/unit/test_csv_parser.py ....                               [ 26%]
project/tests/unit/test_dispatcher.py .......                            [ 41%]
project/tests/unit/test_processors.py ..............                     [ 71%]
project/tests/unit/test_util.py F............                            [100%]

=================================== FAILURES ===================================
__________ TestConvertToNumberIfPossible.test_convert_integer_string ___________

self = <test_util.TestConvertToNumberIfPossible object at 0x7c0791da9700>

    def test_convert_integer_string(self):
        """Тест преобразования строки с целым числом."""
        result = convert_to_number_if_possible("42")
        assert result == 42
>       assert isinstance(result, int)
E       assert False
E        +  where False = isinstance(42.0, int)

project/tests/unit/test_util.py:12: AssertionError
=========================== short test summary info ============================
FAILED project/tests/unit/test_util.py::TestConvertToNumberIfPossible::test_convert_integer_string
========================= 1 failed, 45 passed in 1.34s =========================
